apiVersion: v1
kind: Service
metadata:
  name: ngnix-svc
  labels:
    env: dev
    app: ngnix
spec:
  selector:
    env: dev
    app: ngnix
  ports:
  - port: 80
    #targetPort: 80
    #protocol: TCP
  type: LoadBalancer
